version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tradebinder-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tradebinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - tradebinder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tradebinder"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  tradebinder-network:
    driver: bridge
